### ISSUE TITLE
iOS 8 Deprecated Warning

### ISSUE THREAD

**Issue by jodyheavener** [billgarrison/SORelativeDateTransformer#11]
Just tried this is Xcode 6.1 for iOS 8 and while it works (great, I should add), I'm warned that the following are deprecated:
- NSYearCalendarUnit
- NSMonthCalendarUnit
- NSWeekCalendarUnit
- NSDayCalendarUnit
- NSHourCalendarUnit
- NSMinuteCalendarUnit
- NSSecondCalendarUnit

Just a heads up :smile:

**Comment by marcoscurvello** [comment]
Have you tried switching those up and seeing if it would still work?  @jodyheavener

**Comment by zsy78191** [comment]
Change NSWeekCalendarUnit will make some mistake.
